const normalize = (value) => String(value || "").toLowerCase();

export const getHeaderValues = (headers, name) => {
  if (!Array.isArray(headers)) return [];
  const target = name.toLowerCase();
  return headers
    .filter((item) => String(item?.name || "").toLowerCase() === target)
    .map((item) => String(item?.value || "").trim())
    .filter(Boolean);
};

export const getHeaderValue = (headers, name) => {
  const values = getHeaderValues(headers, name);
  return values[0] || "";
};

export const hasHeader = (headers, name) =>
  getHeaderValues(headers, name).length > 0;

const LIST_HEADERS = [
  "list-id",
  "list-unsubscribe",
  "list-unsubscribe-post",
  "list-help",
  "list-subscribe",
  "list-post",
  "list-archive",
];

export const hasListHeaders = (headers) =>
  LIST_HEADERS.some((name) => hasHeader(headers, name));

export const hasListUnsubscribe = (headers) =>
  hasHeader(headers, "list-unsubscribe") ||
  hasHeader(headers, "list-unsubscribe-post");

export const getPrecedence = (headers) =>
  normalize(
    getHeaderValue(headers, "precedence") ||
      getHeaderValue(headers, "x-precedence")
  );

export const getAutoSubmitted = (headers) =>
  normalize(getHeaderValue(headers, "auto-submitted"));

export const getAutoGenerated = (headers) =>
  normalize(getHeaderValue(headers, "auto-generated"));

export const isAutoSubmitted = (headers) => {
  const autoSubmitted = getAutoSubmitted(headers);
  const autoGenerated = getAutoGenerated(headers);
  return (
    (autoSubmitted && autoSubmitted !== "no") ||
    (autoGenerated && autoGenerated !== "no")
  );
};

export const hasUnsubscribeHeader = (headers) =>
  hasListUnsubscribe(headers) || hasHeader(headers, "unsubscribe");

export const getReplyTo = (headers) => getHeaderValue(headers, "reply-to");

export const hasInReplyTo = (headers) =>
  hasHeader(headers, "in-reply-to") || hasHeader(headers, "references");

export const hasAutoResponseSuppress = (headers) =>
  hasHeader(headers, "x-auto-response-suppress");

export const getListId = (headers) => getHeaderValue(headers, "list-id");

export const hasListId = (headers) => Boolean(getListId(headers));
